### ISSUE TITLE
Error en el tamaño del Html dentro del panel

### ISSUE THREAD

**Issue by Gioyik** [mozillahispano/AddonMozillaHispano#1]
Es un error que hay en cuanto a las Tabs en la actual preview del Addon que de por si el error trata de que las Tabs toman un tamaño dependiendo de si Firefox esta maximizado o en un tamaño personalizado de la ventana. Cuando la ventana de Firefox esta en un tamaño maximizado, no aparece una scrollbar horizontal pero si el tamaño es personalizado si aparece la molesta y fea scrollbar. :P

A alguno mas le pasa, alguien que me lo confirme?

Saludos!

**Comment by willyaranda** [comment]
Nope, a mi no. http://imgur.com/eTLCs

**Comment by Gioyik** [comment]
Esto apariencia en la primera Preview del Addon! Cuando las tabs tenían ese efecto, el color verde y toda la cosa! Ahora con Foundation el cambio de tamaño es Minimo, casi que no notorio. Gracias por confirmarlo!

**Comment by willyaranda** [comment]
Entonces podríamos cerrar este bug? Sólo era para la versión antigua?

**Comment by Gioyik** [comment]
Sip! Lo cerramos y actualizo el Repo! :)
